version: '2'
services:
    marine-app:
        image: marine
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://marine-mysql:3306/marine?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    marine-mysql:
        extends:
            file: mysql.yml
            service: marine-mysql
